api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/config/api_platform/resources'
    formats:
        json:
            mime_types: ['application/json']
        jsonld:
            mime_types: ['application/ld+json']
        html:
            mime_types: ['text/html']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    title: DGT Environmental Label API
    version: 1.0.0
    show_webby: false
    collection:
        pagination:
            client_enabled: true
            enabled_parameter_name: pagination
            client_items_per_page: true
            items_per_page_parameter_name: itemsPerPage
