App\Entity\Vehicle:
    attributes:
        id:
            groups: [read]
        plate:
            groups: [read]
        createdAt:
            groups: [read]
        label:
            groups: [read]
