App\Entity\DownloadedFileLog:
    attributes:
        normalization_context:
            groups: [read]
    collectionOperations:
        get:
            method: GET
    itemOperations:
        get:
            method: GET
