App\Entity\Label:
    attributes:
        normalization_context:
            groups: [read]
    collectionOperations:
        get:
            method: GET
    itemOperations:
        get:
            method: GET
        common_name:
            method: GET
            path: /labels/common_name/{description}
            controller: App\Api\Action\Label\GetLabelByDescription
            read: false
