App\Entity\Label:
    attributes:
        normalization_context:
            groups: [label_read]
    itemOperations:
        get:
            method: GET
            controller: App\Api\Action\GetEnvLabel
            openapi_context:
                summary: Gets the environmental label data of a given ID.
