App\Entity\Vehicle:
    attributes:
        normalization_context:
            groups: [read]
    collectionOperations:
        get:
            method: GET
    itemOperations:
        get:
            method: GET
        latest:
            method: GET
            path: /vehicles/latest/{plate}
            controller: App\Api\Action\GetVehicleLatestEnvLabelByPlate
            read: false
        all:
            method: GET
            path: /vehicles/all/{plate}
            controller: App\Api\Action\GetVehicleAllEnvLabelsByPlate
            read: false
    properties:
        label:
            subresource:
                resourceClass: App\Entity\Label
                collection: false
